[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CANBus"
version = "0.1.0"
description = "A python tool for analysing vehicle CAN data"
dependencies = ["cantools", "diffprivlib", "matplotlib", "pandas"]