sequenceDiagram
Auto->>Tshark-konvertteri: .pcapng Raakadata
Tshark-konvertteri->>Dekooderi: .tsv (Parsittu timestamp, canId ja canData)
Dekooderi->>Visualisoija: .json (Filtteröity ja dekoodattu data)
Visualisoija->>Käyttäjä: analyysin tulokset